# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('crm', '0003_auto_20190602_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role', verbose_name='用户所拥有的角色'),
        ),
    ]
