# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hname', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Lobline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lname', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='lobline',
            name='user',
            field=models.ManyToManyField(to='app01.User'),
        ),
        migrations.AddField(
            model_name='host',
            name='hlid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Lobline'),
        ),
    ]
