# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20190602_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='URL别名'),
            preserve_default=False,
        ),
    ]
