# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')])),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='des',
            field=models.TextField(blank=True, null=True, verbose_name='部门描述'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=32, verbose_name='部门名称'),
        ),
        migrations.AddField(
            model_name='user',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Department'),
        ),
    ]
