# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('weight', models.IntegerField(default=1)),
                ('icon', models.CharField(max_length=64)),
            ],
        ),
    ]
