# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabc', '0002_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('permissions', models.ManyToManyField(blank=True, to='rabc.Permission', verbose_name='角色所拥有的权限')),
            ],
        ),
    ]
