# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('hname', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('hlid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Lobline')),
            ],
        ),
    ]
