# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='hid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='lobline',
            old_name='lid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
    ]
