# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190519_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_column='username', max_length=32, unique=True),
        ),
    ]
