# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190519_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.BooleanField(choices=[(0, '男'), (1, '女')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_column='username', max_length=32, unique=True, verbose_name='姓名'),
        ),
    ]
