# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20190519_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '个人信息', 'verbose_name_plural': '所有用户信息'},
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
