# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20190519_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cukun',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='sale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
